config/routes.rb
Rails.application.routes.draw do
 
    root   'static_pages#home'
    get    '/home',    to: 'static_pages#home'
    get    '/about',    to: 'static_pages#about'
      get    '/contact',    to: 'static_pages#contact'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<head><link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Karma">
</head>

<script>

// Script to open and close sidebar
function w3_open() {
  document.getElementById("mySidebar").style.display = "block";
}
 
function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
}


// Get the modal
var modal = document.getElementById("myModal");

// Get the image and insert it inside the modal - use its "alt" text as a caption
var img = document.getElementById("myImg");
var modalImg = document.getElementById("img01");

var captionText = document.getElementById("caption");
function myFunction(imgs){
  modal.style.display = "block";
  modalImg.src = imgs.src;
  captionText.innerHTML = this.alt;
}

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
  modal.style.display = "none";
}
</script>

<nav class="w3-sidebar w3-bar-block w3-card w3-top w3-xlarge w3-animate-left" style="display:none;z-index:2;width:40%;min-width:300px" id="mySidebar">
  <a href="javascript:void(0)" onclick="w3_close()"
  class="w3-bar-item w3-button">Close Menu</a>
  <a href="#food" onclick="w3_close()" class="w3-bar-item w3-button">Gallery</a>
  <a href="#about" onclick="w3_close()" class="w3-bar-item w3-button">About</a>
</nav>

<!-- Top menu -->
<div class="w3-top">
  <div class="w3-white w3-xlarge" style="max-width:1200px;margin:auto">
    <div class="w3-button w3-padding-16 w3-left" onclick="w3_open()">☰</div>
   <a href=<%=contact_path%>> <div class="w3-right w3-padding-16">Contact</div></a>
    <div class="w3-center w3-padding-16">Handcrafted Wire Designs </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wired Elephant</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    
          
    
           <!--------Bootstrap------>
       
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

           <!--------w3 CSS------>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Karma">
  </head>

  <body>
   
    <%= yield %>
  </body>
</html>

app/views/static_pages/about.html.erb
<!-- Gallery -->
<!--
Gallery is linked to lightbox using data attributes.

To open lightbox, this is added to the gallery element: {data-toggle="modal" data-target="#exampleModal"}.

To open carousel on correct image, this is added to each image element: {data-target="#carouselExample" data-slide-to="0"}.
Replace '0' with corresponding slide number.
-->

<div class="row" id="gallery" data-toggle="modal" data-target="#exampleModal">
  <div class="col-12 col-sm-6 col-lg-3">
    <img class="w-100" src="https://images.unsplash.com/photo-1546853020-ca4909aef454?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&ixid=eyJhcHBfaWQiOjE0NTg5fQ" alt="First slide" data-target="#carouselExample" data-slide-to="0">
  </div>
  <div class="col-12 col-sm-6 col-lg-3">
    <img class="w-100" src="https://images.unsplash.com/photo-1546534505-d534e27ecb35?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&ixid=eyJhcHBfaWQiOjE0NTg5fQ" alt="First slide" data-target="#carouselExample" data-slide-to="1">
  </div>
  <div class="col-12 col-sm-6 col-lg-3">
    <img class="w-100" src="https://images.unsplash.com/photo-1546111380-cfca9a43dd85?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&ixid=eyJhcHBfaWQiOjE0NTg5fQ" alt="First slide" data-target="#carouselExample" data-slide-to="2">
  </div>
  <div class="col-12 col-sm-6 col-lg-3">
    <img class="w-100" src="https://images.unsplash.com/photo-1547288242-f3d375fc7b5f?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&ixid=eyJhcHBfaWQiOjE0NTg5fQ" alt="First slide" data-target="#carouselExample" data-slide-to="3">
  </div>
</div>

<!-- Modal -->
<!--
This part is straight out of Bootstrap docs. Just a carousel inside a modal.
-->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div id="carouselExample" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExample" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExample" data-slide-to="1"></li>
            <li data-target="#carouselExample" data-slide-to="2"></li>
            <li data-target="#carouselExample" data-slide-to="3"></li>
          </ol>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img class="d-block w-100" src="https://images.unsplash.com/photo-1546853020-ca4909aef454?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&ixid=eyJhcHBfaWQiOjE0NTg5fQ" alt="First slide">
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="https://images.unsplash.com/photo-1546534505-d534e27ecb35?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&ixid=eyJhcHBfaWQiOjE0NTg5fQ" alt="Second slide">
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="https://images.unsplash.com/photo-1546111380-cfca9a43dd85?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&ixid=eyJhcHBfaWQiOjE0NTg5fQ" alt="Third slide">
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="https://images.unsplash.com/photo-1547288242-f3d375fc7b5f?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&ixid=eyJhcHBfaWQiOjE0NTg5fQ" alt="Fourth slide">
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExample" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExample" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


<!-- Custom Styling Toggle. For demo purposes only. -->
<div class="switch-wrap">
  <label class="switch">
    <input type="checkbox" id="styleSwitch" onclick="switchStyle();">
    <span class="slider round"></span>
  </label>
  <span class="switch-text">Toggle between <em>Bootstrap defaults</em> and <em>custom styling</em>.</span>
</div>

app/views/static_pages/contact.html.erb
<style>
textarea{
width:100%;

}

.form-s{
width:19%;
}

p , .h4, h2{
font-family: "Karma"
}
span{
  color:blue;
}
</style>

<!-- Container (Contact Section) -->

<div class="container text-center" style="padding-top:10px;"> <%= link_to 'Back to Gallery', home_path, class: "btn btn-primary " %> </div>

<div id="contact" class="container bg-grey" style="margin-top:30px;border-top:none">
    <p id="contactp1" class="text-center h4" style="margin-top:20px;">Interested in purchasing the Wired Elephant? Leave a note below and we will get in touch shortly.</p>
    
    

  <h2 class="text-center";">Inquiries</h2>
  <div class="row" style="margin-top:40px;">
    <div class="col-md-4">
    
      
       <p class="h4"><span class=" text-primary glyphicon glyphicon-home"></span> Proudly made in Sask Canada</p>
        
            <p class="h4"><span class="text-primary glyphicon glyphicon-phone"></span> : 866-950-3506</p>
      <p class="h4"><span class="text-primary glyphicon glyphicon-envelope"></span> :  Support@wilfedo.com</p>
    </div>
    <div class="container">
    <div class="col-md-8 text-center "  >
    <%= form_with(model: @contact, local: true) do |f| %>
         <div class= "row" style="margin-top:10px;">
     <%= f.text_area :name ,maxlength: 255, size: "10x1" ,  placeholder:"Name" %>
    </div>
    <div class= "row" style="margin-top:10px;">
     <%= f.text_area:telephone,maxlength: 255, size: "10x1" ,  placeholder:"Telehone" %>
    </div>
           <div class= "row" style="margin-top:10px;">
     <%= f.text_area:email,maxlength: 255, size: "10x1" ,  placeholder:"Email" %>
    </div>
       
   
    
        <div class= "row" style="margin-top:10px;">
        <%= f.text_area :comment , maxlength: 255, size: "10x5 " , placeholder:"Message" %>
        </div>
   
        <div class= "row" style="margin-top:10px;">
        <%= f.submit "Submit", class: "btn btn-success" %>
        </div>
</div>
  </div>
        </div>
    <%end%>
</div>

  <!-- First Photo Grid-->
  <div class="w3-row-padding w3-padding-16 w3-center" >
    <div class="w3-quarter">
      <img src="assets/0.png" alt="Sandwich" style="width:100%" id="myImg" onclick="myFunction(this)">
      <p></p>
    </div>
    
        <div id="myModal" class="modal">
  <span class="close">&times;</span>
  <img class="modal-content" id="img01">
  <div id="caption"></div>
</div>

    <div class="w3-quarter">
      <img src="assets/21.JPG" alt="Steak" style="width:100%"  id="myImg" onclick="myFunction(this)" >
      <h3></h3>
      <p></p>
    </div>

    <div id="myModal" class="modal">
        <span class="close">&times;</span>
       <img class="modal-content" id="img02">
        <div id="caption"></div>
    </div>

    <div class="w3-quarter">
      <img src="assets/12.JPG" alt="Cherries" style="width:100%" id="myImg" onclick="myFunction(this)">
      <h3></h3>
      <p></p>
    </div>
    
        <div id="myModal" class="modal">
        <span class="close">&times;</span>
       <img class="modal-content" id="img01">
        <div id="caption"></div>
</div>
    <div class="w3-quarter">
      <img src="assets/15.JPG" alt="Pasta and Wine" style="width:100%" id="myImg" onclick="myFunction(this)">
      <h3></h3>
      <p></p>
    </div>
            <div id="myModal" class="modal">
        <span class="close">&times;</span>
       <img class="modal-content" id="img01">
        <div id="caption"></div>
  </div>
<script>
$(window).on('resize', function() {
    if($(window).width() > 900) {
       
        $('#contactp').addClass('h3');
        $('#contactp').removeClass('h4');
       
        $('#contactp1').addClass('h3');
        $('#contactp1').removeClass('h4');
       
    
    }else{
        
        $('#contactp').removeClass('h3');
        $('#contactp').addClass('h4');
        
        $('#contactp1').removeClass('h3');
        $('#contactp1').addClass('h4');
      
    }
})



</script>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Wired Elephant</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Karma">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Karma", sans-serif}
.w3-bar-block .w3-bar-item {padding:20px}

#myImg {
  border-radius: 5px;
  cursor: pointer;
  transition: 0.3s;
}

#myImg:hover {opacity: 0.7;}

/* The Modal (background) */
.modal {
  display: none; /* Hidden by default */
  position: fixed; /* Stay in place */
  z-index: 1; /* Sit on top */
  padding-top: 100px; /* Location of the box */
  left: 0;
  top: 0;
  width: 100%; /* Full width */
  height: 100%; /* Full height */
  overflow: auto; /* Enable scroll if needed */
  background-color: rgb(0,0,0); /* Fallback color */
  background-color: rgba(0,0,0,0.9); /* Black w/ opacity */
}

/* Modal Content (image) */
.modal-content {
  margin: auto;
  display: block;
  width: 80%;
  max-width: 700px;
}

/* Caption of Modal Image */
#caption {
  margin: auto;
  display: block;
  width: 80%;
  max-width: 700px;
  text-align: center;
  color: #ccc;
  padding: 10px 0;
  height: 150px;
}

/* Add Animation */
.modal-content, #caption {
  -webkit-animation-name: zoom;
  -webkit-animation-duration: 0.6s;
  animation-name: zoom;
  animation-duration: 0.6s;
}

@-webkit-keyframes zoom {
  from {-webkit-transform:scale(0)}
  to {-webkit-transform:scale(1)}
}

@keyframes zoom {
  from {transform:scale(0)}
  to {transform:scale(1)}
}

/* The Close Button */
.close {
  position: absolute;
  top: 15px;
  right: 35px;
  color: #f1f1f1;
  font-size: 40px;
  font-weight: bold;
  transition: 0.3s;
}

.close:hover,
.close:focus {
  color: #bbb;
  text-decoration: none;
  cursor: pointer;
}

/* 100% Image Width on Smaller Screens */
@media only screen and (max-width: 700px){
  .modal-content {
    width: 100%;
  }
}
</style>
</head>
<body>

 

<!-- Sidebar (hidden by default) -->
<nav class="w3-sidebar w3-bar-block w3-card w3-top w3-xlarge w3-animate-left" style="display:none;z-index:2;width:40%;min-width:300px" id="mySidebar">
  <a href="javascript:void(0)" onclick="w3_close()"
  class="w3-bar-item w3-button">Close Menu</a>
  <a href="#food" onclick="w3_close()" class="w3-bar-item w3-button">Gallery</a>
  <a href="#about" onclick="w3_close()" class="w3-bar-item w3-button">About</a>
</nav>

<!-- Top menu -->
<div class="w3-top">
  <div class="w3-white w3-xlarge" style="max-width:1200px;margin:auto">
    <div class="w3-button w3-padding-16 w3-left" onclick="w3_open()">☰</div>
   <a href=<%=contact_path%>> <div class="w3-right w3-padding-16">Contact</div></a>
    <div class="w3-center w3-padding-16">Handcrafted Wire Designs </div>
  </div>
</div>


  
<!-- !PAGE CONTENT! -->
<div class="w3-main w3-content w3-padding" style="max-width:1200px;margin-top:70px">
  <!-- About Section -->
  <div class="w3-container w3-padding-32 w3-center" >
    
    <img src="assets/hero.png" alt="Me" class="w3-image" style="display:block;margin:auto" width="800" height="533">
    
    <div id="food">
    <br>
    </div>
    
    <div style="margin-top:60px" >
      <h2  ><b>Gallery</b></h2>
      
   
    </div>
  </div>
  
  <!-- First Photo Grid-->
  <div class="w3-row-padding w3-padding-16 w3-center" >
    <div class="w3-quarter">
      <img src="assets/0.png" alt="Sandwich" style="width:100%" id="myImg" onclick="myFunction(this)">
      <p></p>
    </div>
    
        <div id="myModal" class="modal">
  <span class="close">&times;</span>
  <img class="modal-content" id="img01">
  <div id="caption"></div>
</div>

    <div class="w3-quarter">
      <img src="assets/21.JPG" alt="Steak" style="width:100%"  id="myImg" onclick="myFunction(this)" >
      <h3></h3>
      <p></p>
    </div>

    <div id="myModal" class="modal">
        <span class="close">&times;</span>
       <img class="modal-content" id="img02">
        <div id="caption"></div>
    </div>

    <div class="w3-quarter">
      <img src="assets/12.JPG" alt="Cherries" style="width:100%" id="myImg" onclick="myFunction(this)">
      <h3></h3>
      <p></p>
    </div>
    
        <div id="myModal" class="modal">
        <span class="close">&times;</span>
       <img class="modal-content" id="img01">
        <div id="caption"></div>
</div>
    <div class="w3-quarter">
      <img src="assets/24.JPG" alt="Pasta and Wine" style="width:100%" id="myImg" onclick="myFunction(this)">
      <h3></h3>
      <p></p>
    </div>
            <div id="myModal" class="modal">
        <span class="close">&times;</span>
       <img class="modal-content" id="img01">
        <div id="caption"></div>
  </div>
  
  <!-- Second Photo Grid-->
  <div class="w3-row-padding w3-padding-16 w3-center">
    <div class="w3-quarter">
      <img src="assets/6.JPG" alt="Popsicle" style="width:100%" id="myImg" onclick="myFunction(this)">
      <h3></h3>
      <p></p>
    </div>
    <div class="w3-quarter">
      <img src="assets/2.JPG" alt="Salmon" style="width:100%" id="myImg" onclick="myFunction(this)">
      <h3></h3>
      <p></p>
    </div>
    <div class="w3-quarter">
      <img src="assets/15.JPG" alt="Sandwich" style="width:100%" id="myImg" onclick="myFunction(this)">
      <h3></h3>
      <p></p>
    </div>
    <div class="w3-quarter">
      <img src="assets/9.JPG" alt="Croissant" style="width:100%" id="myImg" onclick="myFunction(this)">
      <h3></h3>
      <p></p>
    </div>
  </div>

  <!-- Pagination
  <div class="w3-center w3-padding-32">
    <div class="w3-bar">
      <a href="#" class="w3-bar-item w3-button w3-hover-black">«</a>
      <a href="#" class="w3-bar-item w3-black w3-button">1</a>
      <a href="#" class="w3-bar-item w3-button w3-hover-black">2</a>
      <a href="#" class="w3-bar-item w3-button w3-hover-black">3</a>
      <a href="#" class="w3-bar-item w3-button w3-hover-black">4</a>
      <a href="#" class="w3-bar-item w3-button w3-hover-black">»</a>
    </div>
  </div>
    -->
  <hr id="about">
         <br><br><br>
  
  <!-- About Section -->
  <div class="w3-container w3-padding-8 w3-center">
    <h3>The Wired Elephant </h3>
        <div >
      
      <p> The Wired Elephant is made from pure copper wire and encorpoprates a single wire design apporoximately 90 meters long. The tusk comes from Canadian cattle , while its eyes are made of onyx stone. The piece feautures a heart of stone from the "????" region and carved by hand and embedded with natural blue sapphire stone ,weighing 4lbs 5.4oz
Dimensión
H-9”x W-61/2”x L-143/4</p>
    </div> <br>
    <img src="assets/0.png" alt="Me" class="w3-image" style="display:block;margin:auto" width="800" height="533" onclick="myFunction(this)">
   
  </div>
  <hr>
  
  <!-- Footer -->
  <footer class="w3-row-padding w3-padding-32">
    <div class="w3-third">
      <h3>FOOTER</h3>
      <p>Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla.</p>
      <p>Powered by <a href="https://www.facebook.com/rocketmanticas" target="_blank">Rocketman High</a></p>
    </div>
  
    <div class="w3-third">
      <h3>BLOG POSTS</h3>
      <ul class="w3-ul w3-hoverable">
        <li class="w3-padding-16">
          <img src="/w3images/workshop.jpg" class="w3-left w3-margin-right" style="width:50px">
          <span class="w3-large">Lorem</span><br>
          <span>Sed mattis nunc</span>
        </li>
        <li class="w3-padding-16">
          <img src="/w3images/gondol.jpg" class="w3-left w3-margin-right" style="width:50px">
          <span class="w3-large">Ipsum</span><br>
          <span>Praes tinci sed</span>
        </li>
      </ul>
    </div>

    <div class="w3-third w3-serif">
      <h3>POPULAR TAGS</h3>
      <p>
        <span class="w3-tag w3-black w3-margin-bottom">Travel</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">New York</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Dinner</span>
        <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Salmon</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">France</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Drinks</span>
        <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Ideas</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Flavors</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Cuisine</span>
        <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Chicken</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Dressing</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Fried</span>
        <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Fish</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Duck</span>
      </p>
    </div>
  </footer>

<!-- End page content -->
</div>


<script>

// Script to open and close sidebar
function w3_open() {
  document.getElementById("mySidebar").style.display = "block";
}
 
function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
}


// Get the modal
var modal = document.getElementById("myModal");

// Get the image and insert it inside the modal - use its "alt" text as a caption
var img = document.getElementById("myImg");
var modalImg = document.getElementById("img01");

var captionText = document.getElementById("caption");
function myFunction(imgs){
  modal.style.display = "block";
  modalImg.src = imgs.src;
  captionText.innerHTML = this.alt;
}

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
  modal.style.display = "none";
}
</script>


</body>
</html>